# Generated by Django 5.0.7 on 2024-07-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('EXPIRED', 'expired'), ('REVOKED', 'revoked')], max_length=50),
        ),
    ]
