# Generated by Django 5.0.7 on 2024-07-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_manager', '0002_alter_accesskey_expiry_date_alter_accesskey_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='date_procured',
            field=models.DateField(auto_now_add=True),
        ),
    ]
